# Generated by Django 3.2.9 on 2021-12-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=300)),
                ('porte', models.CharField(max_length=50)),
                ('func', models.IntegerField()),
                ('data_inicio', models.DateField(verbose_name=['%d-%m-%Y'])),
                ('data_termino', models.DateField(verbose_name=['%d-%m-%Y'])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]

